### ISSUE TITLE
*.g.dart file isn't generated

### ISSUE THREAD

**Issue by almasud** [trevorwang/retrofit.dart#366]
file name: api_client.dart

import 'package:dio/dio.dart';
import 'package:retrofit/http.dart';
import 'package:state_management_bloc/models/album.dart';
part 'api_client.g.dart';

@RestApi(baseUrl: "jsonplaceholder.typicode.com/")
abstract class APIClient {
  factory APIClient(Dio dio) = _APIClient;
 
  @GET("albums")
  Future<List<Album>> getAlbumsData();
}

Bugs:
Target of URI hasn't been generated: 'api_client.g.dart'.
The name '_APIClient' isn't a type and can't be used in a redirected constructor.

**Comment by BTPDarren** [comment]
Do you have

dev_dependencies:
  flutter_test:
    sdk: flutter  
  build_runner:
  retrofit_generator: any

in pubspec.yaml

Then execute flutter pub run build_runner build

**Comment by BTPDarren** [comment]
Should see something like

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Development\Projects\Workspaces\Mobile\btprocket> flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 376ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 111ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 746ms

[INFO] Running build...
[INFO] 1.2s elapsed, 0/16 actions completed.
[INFO] 2.2s elapsed, 0/16 actions completed.
[INFO] 3.3s elapsed, 0/16 actions completed.
[INFO] 9.7s elapsed, 0/16 actions completed.
[INFO] 11.5s elapsed, 0/16 actions completed.
[INFO] 12.5s elapsed, 7/22 actions completed.
[INFO] 13.7s elapsed, 46/46 actions completed.
[INFO] 14.7s elapsed, 68/83 actions completed.
[INFO] Running build completed, took 15.0s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 104ms

[INFO] Succeeded after 15.1s with 0 outputs (92 actions)

PS C:\Development\Projects\Workspaces\Mobile\btprocket>

**Comment by almasud** [comment]
My pubspec.yaml is:

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  retrofit: ^2.0.0
  logger: ^1.0.0
  dio: ^4.0.0
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^2.0.0+2
  build_runner: ^2.0.5
  json_serializable: ^4.1.3

**Comment by teddichiiwa** [comment]
@almasud I added `retrofit_generator: any` in `dev_dependencies` and it started working.
