### ISSUE TITLE
Migrate to dio_http

### ISSUE THREAD

**Issue by woprandi** [trevorwang/retrofit.dart#381]
Since `dio` is not very actively maintained, we should migrate to [`dio_http`](https://pub.dev/packages/dio_http) instead

**Comment by feinstein** [comment]
@trevorwang this change is breaking my app, as it uses dio and now the compiler has some conflicts with generated code, since there are 2 classes with the same names for different packages.

I have seen a commit from 11 days ago in dio, can it really be considered abandoned? This is a very large change for this library, at least the major versions should be increased to reflect such a huge impact.

Remember we can pass dio instances to your lib, so this isn't a small change, even if the API is the same.

**Comment by feinstein** [comment]
@trevorwang I just got informed that dio_http will be discontinued, so we need to rollback Retrofit to dio, as the creator of dio_http is a contributor there now.

**Comment by woprandi** [comment]
@feinstein How did you get this information about `dio_http` ?

**Comment by jgoyvaerts** [comment]
Short update:
https://github.com/flutterchina/dio was abandoned for more than 6 months, so I forked it to https://github.com/dart-tools/dio_http
A few weeks ago, Wendux, the original maintainer showed up again and added me as a contributor to https://github.com/flutterchina/dio .

Given that he's active again and he added another contributor in case he goes missing again, I'm fine with sunsetting/archiving dio_http and porting the fixes over to dio.

Still have to port some performance improvements over from dio_http to dio, but you should be fine switching back to dio

**Comment by woprandi** [comment]
@jgoyvaerts Thanks for the update, I'm very concerned about performance patchs added to `dio_http` and we'd switching back when they are ported to `dio`.

**Comment by woprandi** [comment]
@feinstein Your app should have a `pubspec.lock` to avoid a involuntary update in your dependencies.

**Comment by feinstein** [comment]
> @feinstein How did you get this information about `dio_http` ? 

I spoke with the creator of `dio_http` and asked him to reach you. He's now a contributor on `dio`.

**Comment by feinstein** [comment]
> @feinstein Your app should have a `pubspec.lock` to avoid a involuntary update in your dependencies. 

I have a pubspec.lock (can we not have it?), but still people change branches and modify code, run `build_runner` with `pub get` as they change branches.

Since we use the [caret syntax](https://dart.dev/tools/pub/dependencies#caret-syntax), the package was automatically updated without anyone noticing, breaking builds. This froze half my team for an entire day while I was able to investigate what was going on.

This change should have been made with a major version number upgrade (3.0.0) so no one with a caret version such as `^2.0.0` would be affected by `pubspec.lock` silently updating to `2.1.0`.

**Comment by woprandi** [comment]
@feinstein The lock file guarantee you a reproductible build. The exact version of all dependencies (direct or not) are written in it. So a package cannot be upgraded automatically just with `pub get`. https://dart.dev/guides/packages#upgrading-a-dependency. 
Anyway I agree with you that this change should have been made with a major version number.

**Comment by feinstein** [comment]
Yeah, but unfortunately sometimes people push the `pubspec.lock` file into the source control, and it passes code reviews. In theory it shouldn't be updated, but sometimes someone deletes `pubspec.lock` to force an update with git dependencies from internal libraries. It's an edge case we are dealing with for now.

Anyway, I appreciate the support and hope we can get back to `dio` soon.

**Comment by jgoyvaerts** [comment]
> @jgoyvaerts Thanks for the update, I'm very concerned about performance patchs added to `dio_http` and we'll switch back when they are ported to `dio`.

@woprandi Fixes have been ported to dio (well you PRd it technically  👍 ) and package published to pub.dev so should be safe to switch back to dio
