### ISSUE TITLE
error:type 'UnspecifiedInvalidResult' is not a subtype of type 'LibraryElementResult' in type cast

### ISSUE THREAD

**Issue by lvzh321** [trevorwang/retrofit.dart#429]
update to version:  
retrofit:3.0.0      
retrofit_generator: 3.0.0+2
build_runner: any
flutter pub run build_runner build =>error:type 'UnspecifiedInvalidResult' is not a subtype of type 'LibraryElementResult' in type cast
the source_gen lib version is 1.0.3

old version:
retrofit:2.0.0      
retrofit_generator: 2.0.0+2
build_runner: any
flutter pub run build_runner build =>success
the source_gen lib version is 1.0.2

version between retrofit_generator and build_runner is conficting

**Comment by mohan-sai-manthri-sg** [comment]
Facing the same issue here, Any updates on this?

**Comment by ahmed56734** [comment]
I have same issue and I am stuck because of this

**Comment by ahmed56734** [comment]
C:\Users\ahmed\AndroidStudioProjects\Damen_APP>flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 352ms

[INFO] Precompiling build script......
[WARNING] ../../flutter_sdk/.pub-cache/hosted/pub.dartlang.org/retrofit_generator-2.0.1/lib/src/generator.dart:215:46: Error: Getter not found: 'CacheControl'.
    final annotation = _typeChecker(retrofit.CacheControl)
                                             ^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 5.1s

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
