### ISSUE TITLE
analyzer 4.1.0

### ISSUE THREAD

**Issue by erabti** [trevorwang/retrofit.dart#473]
Update analyzer version to latest version `4.1.0`

**Comment by BenCherif** [comment]
Any updates about this ?

**Comment by ilovelinux** [comment]
Analyzer has been upgraded to 4.0.0 in commit https://github.com/trevorwang/retrofit.dart/commit/da0f4933ed30f70f958426831bad49fd43a2d66f (#472). I hope there will be a upgrade to 4.1.0 soon.

**Comment by BenCherif** [comment]
we hope there will be an upgrade to 4.1.0 as soon as possible

**Comment by paricleu** [comment]
It looks like the current master already supports analyzer <5.0.0 but it's not on pub.dev yet because of a failed test because the [pub command ](https://github.com/trevorwang/retrofit.dart/runs/6735173196?check_suite_focus=true) can't be found.
I have no idea how to fix that so maybe @trevorwang can do something about this?

**Comment by jdebecka** [comment]
Is there any time estimation when this could be possibly merged? :)

**Comment by rokk4** [comment]
Would be nice to have this on pub.dev

**Comment by trevorwang** [comment]
published on pub.dev now
